.editorconfig

GitHub Issue: #13 
1. Open up any editor that has `editorconfig` file support, it should follow all of the rules.

devtools(common): add editorconfig support

---

src/components/parameter-range-selector/index.js
src/components/parameter-range-selector/style.css

Adds tooltips to the parameters range sliders on the filters (and anywhere where those filters are being used)

fix(slider): add tooltips to param sliders

---

src/components/main-drawer.js

- Look at the elements in drawer menu on the left, you should be able to see and click only the routes that on `src/routes/index.js` have `drawerLabel`.

fix(menu): do not show routes without label on main drawer

---

services/frontend/src/components/bottom-navbar.js
services/frontend/src/components/input-autocomplete.js
services/frontend/src/components/main-drawer.js
services/frontend/src/routes/account/index.js
services/frontend/src/routes/block-producers/index.js
services/frontend/src/routes/login/index.js
services/frontend/src/routes/not-found/index.js
services/frontend/src/routes/settings/index.js

- Look on `src` folder for any `translate` uses from `react-i18next`, there should be none at all.

refactor(i18n): change all instances of translate to withNamespaces

---

services/frontend/src/components/block-producer-card.js
services/frontend/src/components/block-producer-radar.js

This PR includes changes `/block-producers` url.
Ticket #84

style(BP Cards) apply visual tweaking to block producer cards

---

services/frontend/src/components/block-producer-radar.js

1. Open up the main page and go to `Block Producers`.
1. Radars should look complete with no cutoff anywhere in the chart.
1. Add radars to the compare tool.
1. All radars should look complete with no cutoffs.

fix(webapp): adjust bottom padding on radar chart

---

services/frontend/package.json
services/frontend/src/components/app-bar.js
services/frontend/src/components/layout.js
services/frontend/src/components/main-drawer.js
services/frontend/src/language/en.json
services/frontend/src/language/es.json
services/frontend/src/models/blockProducers.js
services/frontend/src/routes/block-producers/compare-tool-toggle.js
services/frontend/src/routes/block-producers/index.js

1. Open up the homepage.
1. Side menu should be hidden away.
1. Clicking to block producers, should appear an option to hide/show the compare tool.
1. Clicking the hide/show compare tool switch, should toggle visibility of compare tool.
1. Filter sliders should not be visible, nor be in the DOM at all.

fix(webapp): adjust sidebar to alpha release version

---

scripts/start.sh

Add `yarn install` before running `yarn start` in the start script

fix(scripts): add yarn install to start script

---

services/demux/src/services/update-bps/index.js
services/frontend/.env
services/frontend/src/components/block-producer-card.js
services/frontend/src/components/compare-tool/compare-graph-view.js
services/frontend/src/components/compare-tool/compare-slider-view.js
services/frontend/src/components/compare-tool/index.js
services/frontend/src/models/blockProducers.js
services/frontend/src/routes/block-producers/index.js
services/frontend/src/services/bps.js
services/frontend/src/services/graphql.js

Issue #17 
**IMPORTANT NOTE: THIS STILL NEEDS WORK!**
This still needs a place to point to consume the block producers from, right now the `.env` file is pointing at `localhost`, but we need a way to set this env var up on the different environments.
If this gets pushed, it will break production until we can configure a `graphql` consumable endpoint.

feat(webapp): consume block producers from graphql endpoint

---

services/frontend/src/routes/home/cover.js
services/frontend/src/routes/home/index.js
services/frontend/src/routes/home/subTopic.js

#
1. Open up the app in desktop.
1. Go to home page.
1. Resize the browser to notice the max width applied.
#

style(home) apply max width to rows in home page

---

services/frontend/src/components/block-producer-card.js
services/frontend/src/components/compare-tool/compare-graph-view.js
services/frontend/src/models/blockProducers.js
services/frontend/src/routes/block-producers/block-producer-profile.js
services/frontend/src/routes/block-producers/index.js

#54 
1. Open up the block producers page.
1. Scroll all the way down and look for the `Load More` button
1. Hit that button, 10 more block producers should appear.
1. Hit the button again, and 10 more should appear, and so on until we run out of block producers.

fix(web): improve DOM performance loading less elements at once

---

services/frontend/src/routes/index.js

#159 
1. Open the side menu.
1. Confirm that the settings route is no longer visible.

fix(web): remove unused settings route

---

services/frontend/src/language/en.json
services/frontend/src/language/es.json
services/frontend/src/routes/block-producers/index.js

Update the FAB (floating action button) in the block producers listing page to show up a visibility icon on and off with a tooltip.
#142
1. Open the drawer menu.
2. Click in the "Block Producers" link.
3. The FAB is placed in the bottom right corner of the page.
4. Hover the FAB to see the tooltip.
5. Click the FAB to see how the icon and tooltip toggles and the tool is shown/hidden accordingly.

Update FAB in BPs page

---

contracts/eoseosrateio/eoseosrateio.cpp

-  Allow partial ratings
-  Table name parameter added within action _erase_ 
-  Proxy restriction code deleted, due to is not filter accounts properly
-  Use (_self, _self.value) for the tables' memory allocation model
eosio-cpp eoseosrateio.cpp -o eoseosrateio.wasm -abigen -I  _**{CONTRACT PATH}**_
cleos -u http://monitor.jungletestnet.io:8888 set contract eoseosrateio . -p eoseosrateio@active
cleos -u http://monitor.jungletestnet.io:8888 push action eoseosrateio rateproducer '{ "user": "eoseosrateio", "bp": "alohaeostest", "ratings_json": "{\"transparency\":8,\"infrastructure\":8,\"trustiness\":7,\"development\":6,\"community\":10}" }' -p eoseosrateio@active
cleos -u http://monitor.jungletestnet.io:8888 push action eoseosrateio rateproducer '{ "user": "eoseosrateio", "bp": …

Issue 226 User cannot push partials ratings

---

docker-compose.staging.yml
docker-compose.yml
services/hapi/src/index.js
services/hasura/migrations/1582950844052_create_action_rateProducer/down.yaml
services/hasura/migrations/1582950844052_create_action_rateProducer/up.yaml
services/hasura/migrations/1582994080171_modify_action_rateProducer_to_rateProducer/down.yaml
services/hasura/migrations/1582994080171_modify_action_rateProducer_to_rateProducer/up.yaml
services/hasura/migrations/1582994256642_modify_action_rateProducer_to_rateProducer/down.yaml
services/hasura/migrations/1582994256642_modify_action_rateProducer_to_rateProducer/up.yaml
services/hasura/migrations/1583004430995_modify_action_rateProducer_to_rateProducer/down.yaml
services/hasura/migrations/1583004430995_modify_action_rateProducer_to_rateProducer/up.yaml
services/hasura/migrations/1583004453318_modify_action_rateProducer_to_rateProducer/down.yaml
services/hasura/migrations/1583004453318_modify_action_rateProducer_to_rateProducer/up.yaml
services/hasura/migrations/1583004636939_modify_action_rateProducer_to_rateProducer/down.yaml
services/hasura/migrations/1583004636939_modify_action_rateProducer_to_rateProducer/up.yaml

This PR exposes a new motation to trigger a hapi endpoint that will update a blockproducer's stats and a user's ratings.
1. run the following mutation:
```
mutation rateProducer {
rateProducer(ratingInput: { producer: "junglemorpho", user: "tetogomezeos" }) {
message
}
}
```

Add hasura actions

---

services/demux/yarn.lock
services/hapi/yarn.lock

**We found potential security vulnerabilities in your dependencies.**
Bumps [acorn](https://github.com/acornjs/acorn) from 7.1.0 to 7.1.1.
Bumps [acorn](https://github.com/acornjs/acorn) from 5.7.3 to 5.7.4.

update acorn dependancies 

---

services/hapi/src/libs/sync-proxies.js
services/hasura/migrations/1584293813117_create_table_public_proxies/down.yaml
services/hasura/migrations/1584293813117_create_table_public_proxies/up.yaml

#343 Save info on registered proxies
1. Run `node /services/hapi/src/libs/sync-proxies.js`
2. fetch data from the table: `proxies`

add proxies table and script

---

contracts/rateproducer/README.md
contracts/rateproducer/rateproducer.cpp
contracts/tests/package.json
contracts/tests/test.js
contracts/tests/test_average.js
contracts/tests/test_unreg_bp.js

Clear ratings for inactive producers
this fix the issue #300  
When a bp become inactive, the contract still storage the votes related to inactive bp
theres a new action `rminactive` which can periodic check and clean the dirty data
`cleos -u http://monitor.jungletestnet.io:8888 push action rateproducer rminactive '[]' -p rateproducer@active`
1. go inside tests folder
2. you need to assign the priv key for the variable ```rateproducer_priv_key``` within the file  test_unreg_bp.js
3. execute
```
yarn add eosjs
yarn install
yarn test_unreg_bp
```

 Clear ratings for inactive producers

---

services/frontend/src/components/app-bar.js
services/frontend/src/models/BlockProducer/blockProducers.js
services/frontend/src/routes/block-producers/block-producer-profile.js
services/frontend/src/routes/block-producers/block-producer-rate.js
services/frontend/src/routes/block-producers/index.js
services/frontend/src/routes/home/index.js
services/frontend/src/routes/proxies/index.js

1. go to EOS RATE web app (sort options shouldn't be shown)
2. go to BPs list (see Sort options)

refactor(FE): hide or show sort option

---

makefile
scripts/stop.sh

1. run `make start`
1. run `make stop`
1. docker services should no longer be running locally

add stop script

---

kubernetes/demux-deployment.yaml
kubernetes/demux-service.yaml
kubernetes/frontend-deployment.yaml
kubernetes/frontend-service.yaml
kubernetes/hapi-deployment.yaml
kubernetes/hapi-service.yaml
kubernetes/hasura-deployment.yaml
kubernetes/hasura-service.yaml
kubernetes/networkpolicy.yaml
kubernetes/pgweb-deployment.yaml
kubernetes/pgweb-service.yaml
kubernetes/postgres-deployment.yaml
kubernetes/postgres-service.yaml

uses kubernetes to deploy EOS-rate in a k8s cluster.
Still TODO:
* Allocate dynamic storage instead of a local directory for
volumes.
* Allocate dynamic external IPs for exposing services.
refs #224 and #https://github.com/edenia/openstack-docs/issues/18.
depends on the frontend container created in #366.
1. kubectl create -f kubernetes/
1. kubectl port-forward service/frontend 80:80
1. visit {external_ip}
1. you should see the eos rate page

improvement: add kubernetes deployment and service files

---

docker-compose.yml
kubernetes/hasura-deployment.yaml

Secure GraphQL endpoint #317
1. setup an HASURA_GRAPHQL_ADMIN_SECRET environment variable
2. run `docker-compose -up -d`
3. run `hasura console --endpoint http://localhost:8088 --admin-secret $HASURA_GRAPHQL_ADMIN_SECRET `

chore: add hasura admin secret configuration

---

kubernetes/cronjob.yaml

Cron job hapi

---

services/frontend/src/components/card.js
services/frontend/src/components/compare-tool/index.js
services/frontend/src/routes/block-producers/block-producer-rate.js
services/frontend/src/routes/home/index.js

- Change Card Add button label to 'Add to Vote'
- Add padding to average and rate info on card header component
- Change button color label to compare voting tool
- Move 'Publish Rating' and 'Cancel' button from the right column to the left column (tablet and desktop version)
- Add padding to home page
2. go to the home page with padding (mobile version)
3. go to BPs list page and see card component
4. go to Rate page and see the page using the desktop version and then mobile version

refactor(FE): fix UI issues

---

services/frontend/src/components/app-bar.js
services/frontend/src/components/bp-chip-avatar.js
services/frontend/src/components/compare-tool/compare-graph-view.js
services/frontend/src/components/compare-tool/index.js
services/frontend/src/language/en.json
services/frontend/src/language/es.json
services/frontend/src/models/BlockProducer/blockProducers.js
services/frontend/src/models/Proxy/proxy.js
services/frontend/src/models/user.js
services/frontend/src/routes/block-producers/block-producer-profile.js
services/frontend/src/routes/block-producers/block-producer-rate.js
services/frontend/src/routes/block-producers/index.js
services/frontend/src/routes/block-producers/slider-rating-section.js
services/frontend/src/routes/home/subTopic.js
services/frontend/src/routes/proxies/index.js
services/hapi/src/libs/sync-bps.js

- change BP JSON texts #435
- Show when users haven't voted for 21 block producers ratings in a user friendly way #384
- Tooltips next to rating categories not visible #430
- View button on Proxy card does not work #434
- add functionality to close compare tool component
- clear BPs select after use logout
- Increase timeout to get bp information
1. run project `make dev`
2. test the eos rate web app

Fix issues

---

services/hapi/src/libs/sync-bps.js

Some BPs show they have no bp.json when they actually do #429
This change skips saving empty `bp.json` files

skip persisting empty bpjson response

---

services/hapi/src/libs/sync-bp-stats.js

It avoids to update the new votes when using the mainnet.
refs #420
#
1.
1.
1.

Fixes a inconsistent environment variable

---

services/frontend/src/language/en.json
services/frontend/src/language/es.json
services/frontend/src/routes/about/index.js
services/frontend/src/routes/help/index.js
services/frontend/src/routes/home/cover.js

#470 #471 
Add content for Help and About page
1. go to `http://localhost:3000`
1. see Help page content and About page content

Add content Help and About page

---

kubernetes/common/cronjob.yaml
kubernetes/common/hapi-deployment.yaml
kubernetes/common/hasura-deployment.yaml
kubernetes/common/pgweb-deployment.yaml
kubernetes/common/postgres-deployment.yaml
kubernetes/production/frontend-deployment.yaml
kubernetes/testing/demux-deployment.yaml
kubernetes/testing/frontend-deployment.yaml
services/frontend/.env.staging

update the URLs that point to the new domain names, and force to pull the docker images so we can keep then updated.
refs #401
#
1.
1.
1.

Update URLs and pull policy

---

utils/meta.mk

The docker hub repository image names did not specify they are related to eos-rate

Docker image names not specific enough for public repository

---

webapp/src/components/InputAutocomplete/styles.js
webapp/src/config/polar-radar-config.js
webapp/src/layouts/Dashboard/index.js
webapp/src/routes/BlockProducers/index.js
webapp/src/routes/BlockProducers/styles.js
webapp/src/routes/Proxies/index.js
webapp/src/routes/Proxies/styles.js
webapp/src/theme/breakpoints.js
webapp/src/utils/get-bp-radar-data.js
webapp/src/utils/modeled-bp-data.js

- Add logic for 'go to top' button
- Add google analitycs
- Format average number to one decimal (example: `Transparency: 6.5`) 
- Add labels in Polar Graph
- Add mini margin to inputSearch
- Add new breakpoint in order to hadler 1110 px resolution
1. go to `localhost:3000`
1. test the webapp

fix(webapp): add GA and styling UI

---

webapp/src/components/CompareTool/CompareGraphView.js
webapp/src/components/CompareTool/CompareSliderView.js
webapp/src/components/CompareTool/styles.js
webapp/src/theme/breakpoints.js

1. go to localhost:3000
1. test selecting some BPs and open compare tool

fix(webapp): Add styling to compare tool for lg screens
