webapp/.eslintrc, webapp/src/app.js, webapp/src/components/app-bar.js, webapp/src/components/layout.js, webapp/src/components/main-drawer.js, webapp/src/mock/bps.js, webapp/src/models/blockProducers.js, webapp/src/models/index.js, webapp/src/routes/all-bps/AllBps.js, webapp/src/routes/rate/index.js, webapp/src/routes/rate/rate.js, webapp/src/services/bps.js, webapp/src/utils/getBPRadarData.js, webapp/src/utils/getColorFromName.js
This is a preliminary work, it needs a lot still, but this is the foundation to create the main view, we still need to get rid of unnecessary routes, this still needs work!
I'm putting this PR out there so that anyone can track it's progress.
=> feat(webapp): create all BPs view

package.json, yarn.lock
These are super small fixes needed for consistency in the project builds and regular daily work.
=> Small needed ci fixes

.eslintrc, src/components/bottom-navbar.js, src/components/checkbox.js, src/components/icon/index.js, src/components/select.js, src/routes/account/index.js, src/routes/home/index.js, src/routes/login/index.js, src/routes/not-found/index.js
rel https://github.com/eoscostarica/rate.eoscostarica.io/issues/10
=> refactor(common): comply to standardjs

src/app.js, src/components/main-drawer.js, src/routes/block-producers/filter-box.js, src/routes/block-producers/index.js, src/routes/index.js
=> feat(navigation): add support for custom sidebar items per route

src/app.js
This fixes an issue happening on App.js with dynamic routes
=> fix(common): add keys to dynamic routes in app

package.json, src/components/block-producer-radar.js, src/components/parameter-range-selector/index.js, src/components/parameter-range-selector/style.css, src/config/comparison-parameters.js, src/mock/bps.js, src/routes/block-producers/filter-box.js, src/utils/getBPRadarData.js, yarn.lock
This will add dynamically managed block producer parameter sliders with components, plus it also adds style to the radars.
=> feat(sidebar): add dynamically managed bp param sliders

package.json, src/app.js, src/models/session.js, src/routes/account/index.js, src/services/scatter.js, yarn.lock
This is a work in progress.
But you can already click on the fingerprint icon to test.
closes #5
=> feat(common): scatter integration

src/components/main-drawer.js, src/config/theme.js
This should fix the behavior of the drawer
=> fix(drawer): avoid closing drawer when submenu is available

src/components/block-producer-card.js
small refactor to pull radar labels from config
=> refactor(radar): use config comparison parameters on radars

src/utils/getBPRadarData.js
=> ui(radar): set line tension to .3 and alpha to .9

package.json, yarn.lock
- Remove `node_modules`
- Install all dependencies.
- No warnings or errors should come up.
- Run the project to make sure everything's ok `yarn start`
=> fix(ci): fix eslint and react-scripts duplicated dependencies

services/frontend/package.json, services/frontend/src/components/block-producer-radar.js, services/frontend/src/config/radar.js, services/frontend/src/index.js, services/frontend/yarn.lock
**Steps to test**
- Look on `src/components/block-producer-radar.js` file and `src/config/radar.js` file, verify the style on the url `/block-producers`
=> style(radar) apply style to radar according to design

services/frontend/src/components/layout.js, services/frontend/src/components/main-footer.js
#71 
1. Go into each of the URLs, footer should always be there, and always inside the main and in the bottom.
=> fix(webapp): constrain footer to main container

services/demux/src/MongoActionReader.ts, services/demux/src/MongoBlock.ts, services/demux/src/effects.ts, services/demux/src/index.ts, services/demux/src/services/data-cleaner.ts, services/demux/src/updaters.ts, services/demux/yarn.lock
1. Any PR submitted has issues on Travis, if this works, Travis should build perfectly fine.
=> fix(ci): remove unnecessary semicolons from dmux service

services/frontend/src/components/block-producer-card.js
There's a security warning we need to fix:
=> fix(webapp): add rel="noopener noreferrer" to _blank anchors

services/frontend/src/components/compare-tool/compare-graph-view.js, services/frontend/src/components/compare-tool/compare-slider-view.js, services/frontend/src/components/compare-tool/index.js, services/frontend/src/config/theme.js
1. Open up the app and the dev tools.
1. No warning about typography should appear at all in the console.
=> fix(webapp): remove typography and i18n warnings

services/frontend/src/components/video.js, services/frontend/src/routes/home/cover.js, services/frontend/src/routes/home/index.js, services/frontend/src/routes/home/subTopic.js
1. Open up the webapp.
1. Open up dev-tools.
1. While in homepage, no errors/warnings should appear in the console.
=> Homepage errors

services/frontend/src/config/radar.js
Added functions in order to be more readable the code .
=> refactor(radar) clean up radar settings

readme.md
Update alias with old url: 
```
alias cleos='docker exec -i eoslocal_eosio cleos -u http://eosio:8888 --wallet-url http://eos-wallet:8901'
```
to last url version
```
alias cleos='docker exec -i eoslocal_eosio cleos -u http://eosio:8888 --wallet-url http://wallet:8901'
```
=> docs(readme) update readme with right eoslocal_eosio alias

.github/pull_request_template.md
1. Creating new PRs, should have this structure in it.
=> feat: add pr template for github

services/frontend/src/components/input-autocomplete.js, services/frontend/src/routes/block-producers/block-producer-profile.js
#110 
1. Load the app
1. Start typing on the search field
1. Click or navigate and press enter on the desired block producer
1. It should navigate you to the block producer profile page.
=> Search refactor

docker-compose.staging.yml, services/frontend/.env.staging
#107
1. the netlify link should work fine
=> fix: correct staging configuration

services/frontend/src/components/app-bar.js, services/frontend/src/language/en.json, services/frontend/src/language/es.json, services/frontend/src/models/session.js, services/frontend/src/routes/account/index.js, services/frontend/src/routes/index.js, services/frontend/src/services/scatter.js
#
1. Create account in [jungle](https://monitor.jungletestnet.io/#home).
1. Set up the credentials in local Scatter.
1. Open up the app in desktop.
1. Click in the fingerprint icon in the right top corner.
#
=> feat(frontend): account page

services/frontend/public/index.html, services/frontend/public/manifest.json
Update site title in favor of better SEO.
1. Visit eosrate.
1. Check the page title.
=> feat(frontend): update site title for SEO

services/frontend/src/config/comparison-parameters.js, services/frontend/src/routes/block-producers/block-producer-rate.js
Corrects the rating parameters that are being sent to the contract #209
1. Open the [app](https://5df083f01cf143000cdb6931--eosrate.netlify.com) and start session with scatter or any other wallet.
1. Navigate to the blocks producers page.
1. Click on any of the BPs name.
1. Click the rate button.
1. Select some values from the sliders.
1. Click the Rate button to send the rating.
=> fix(frontend): correct rate parameters

services/frontend/src/components/app-bar.js, services/frontend/src/components/language-select.js, services/frontend/src/components/main-footer.js
#
1. Go to eosrate home page
2. scroll down and use language select input
=> refactor(FE): add style to language component

services/frontend/.env.staging
#242 
1. Build and start the project.
1. Every api and graphql call should work as expected.
=> fix: use new env url scheme for stage services in env file

contracts/rateproducer/rateproducer.cpp
=> set contract who pays for ram required to rate

services/frontend/package.json, services/frontend/src/components/layout.js, services/frontend/src/config/google-analitycs-module.js, services/frontend/yarn.lock
=> Add google analitycs module

services/demux/src/index.js, services/frontend/.env.staging
=> try kevin advise

services/demux/src/index.js, services/frontend/.env.staging
Reverts eoscostarica/eos-rate#251
=> Revert "try kevin advise"

services/frontend/src/components/main-footer.js, services/frontend/src/language/en.json, services/frontend/src/language/es.json
#
1. run FE project
1. go to home page
1. scroll down and see footed
=> refactor(FE): add footer legend (update footer)

services/demux/package.json, services/demux/yarn.lock
set-value vulnerability #230
lodash vulnerability #229
1. resolved github security warnings
=> services(demux) update packages

services/frontend/src/components/block-producer-radar.js, services/frontend/src/config/theme.js, services/frontend/src/language/en.json, services/frontend/src/language/es.json, services/frontend/src/models/blockProducers.js, services/frontend/src/routes/block-producers/block-producer-profile.js, services/frontend/src/routes/block-producers/general-information-profile.js, services/frontend/src/routes/block-producers/index.js
1. Login in the EOS Rate web app
2. go to block producers page
3. select a block producer and see the information
=> refactor(FE): refactor UI, remove mock data

services/frontend/src/components/block-producer-radar.js, services/frontend/src/config/theme.js, services/frontend/src/language/en.json, services/frontend/src/language/es.json, services/frontend/src/models/blockProducers.js, services/frontend/src/routes/block-producers/block-producer-profile.js, services/frontend/src/routes/block-producers/general-information-profile.js, services/frontend/src/routes/block-producers/index.js
=> refactor(FE): refactor UI, remove mock data (#266)

services/frontend/.env.staging, services/frontend/package.json, services/frontend/src/components/app-bar.js, services/frontend/src/components/block-producer-card.js, services/frontend/src/components/block-producer-radar.js, services/frontend/src/components/compare-tool/compare-graph-view.js, services/frontend/src/components/compare-tool/compare-slider-view.js, services/frontend/src/components/compare-tool/index.js, services/frontend/src/components/input-autocomplete.js, services/frontend/src/components/rate-slider.js, services/frontend/src/language/en.json, services/frontend/src/language/es.json, services/frontend/src/routes/account/index.js, services/frontend/src/routes/block-producers/block-producer-profile.js, services/frontend/src/routes/block-producers/block-producer-rate.js, services/frontend/src/routes/block-producers/compare-tool-toggle.js, services/frontend/src/routes/block-producers/filter-box.js, services/frontend/src/routes/block-producers/general-information-profile.js, services/frontend/src/routes/block-producers/index.js, services/frontend/src/routes/settings/index.js, services/frontend/yarn.lock
#277
#180
#262 
- Refactor Slider rate component
- Update block-producer.js (use hook)
- Add tooltips property in react-chartjs-2 options
- Upgrade material UI package (Migration from v3 to v4)
- Upgrade react-chartjs-2 package
- Update material UI utils functions
- Validate block producer Profile
- Validate block producer list page
- Validate mobile version
#
1. go to EOS Rate web app
2. login
3. go to block producers page (in this page to move mouse hover radar card and see tooltip)
4. choose one block producer and click it
5. click Rate this BP button (in this page to move mouse hover radar card and see tooltip)
6. see the new design for slider rate component
=> Block Producer

.github/workflows/push-staging-environment.yaml
=> fix: add yaml file for github actions

services/frontend/src/components/block-producer-card.js, services/frontend/src/language/en.json, services/frontend/src/language/es.json, services/frontend/src/routes/block-producers/block-producer-profile.js, services/frontend/src/routes/block-producers/general-information-profile.js, services/frontend/src/routes/block-producers/index.js, services/frontend/src/services/bps.js
#156 
1. Go to eosrate.io
1. click "Rate Block Producers" button
1. see all bps (with bpjson and without bpjson)
=> refactor(FE): show block producer without bpJson

services/frontend/src/components/app-bar.js, services/frontend/src/components/compare-tool/compare-graph-view.js, services/frontend/src/components/compare-tool/index.js, services/frontend/src/components/radar.js, services/frontend/src/language/en.json, services/frontend/src/language/es.json, services/frontend/src/models/BlockProducer/blockProducers.js, services/frontend/src/models/user.js, services/frontend/src/routes/block-producers/general-information-profile.js, services/frontend/src/routes/block-producers/index.js
#283 
1. login to EOS RATE web app
2. go to BPs list page
3. see all bp list in the voting portal
=> refactor(FE): show bps voted for user

services/frontend/src/components/card.js, services/frontend/src/routes/proxies/index.js
1. go to EOS RATE 
2. go to BPs list page
3. see mobile version and desktop version
=> Card component mobile

services/frontend/src/components/filter-select.js, services/frontend/src/language/en.json, services/frontend/src/language/es.json, services/frontend/src/utils/sortedBy.js
#Add new filters
1. go to EOS RATE
2. go to BPs list page
3. use Sort functionality
=> Add new filters

services/frontend/src/language/en.json
#Change label rate card name
1. go to EOS RATE
2. go to BPs list page
3. see Ratings label on the card component
=> change label rate card name

services/frontend/src/components/compare-tool/compare-slider-view.js
1. go to EOS RATE web page
2. login
3. go to bps list
=> Validate bps empty object

services/frontend/src/components/bp-chip-avatar.js, services/frontend/src/components/compare-tool/compare-graph-view.js, services/frontend/src/components/radar.js, services/frontend/src/models/user.js, services/frontend/src/routes/block-producers/index.js, services/frontend/src/routes/block-producers/slider-rating-section.js, services/frontend/src/routes/proxies/index.js, services/frontend/src/services/bps.js
#382
#383
#385
- Create ProducerChipAvatar component
- Improve performance for BPs list and Proxies list avoiding unnecessary re-renders
- Add Producer name into Radar tooltip view
- Validate getUserChainData function
- Add max height and a scroll in order to avoid overlapping for producer chip list  
1. go to EOS RATE web app
2. login and use all functionality
=> Fix several issues

services/frontend/src/language/en.json, services/frontend/src/language/es.json
Update page title strings for enhanced Search Engine Indexing
=> update page titles for SEO

services/frontend/package.json, services/frontend/src/utils/ualAuthenticators.js, services/frontend/yarn.lock
#388 
1. Click to login EOS RATE webapp
=> Add ual anchor

services/frontend/src/language/en.json, services/frontend/src/language/es.json, services/frontend/src/routes/home/cover.js, services/frontend/src/routes/home/subTopic.js
- update home texts
- change URL video
2. go to the home and check new texts changes
3. see the new video
=> update home texts

services/frontend/src/language/en.json, services/frontend/src/language/es.json, services/frontend/src/routes/home/cover.js, services/frontend/src/routes/home/subTopic.js
=> Refactor home text

services/frontend/src/models/BlockProducer/blockProducers.js, services/frontend/src/routes/block-producers/block-producer-profile.js
#Loading BP data
2. open browser as incognito and paste this URL `http://localhost:3000/block-producers/spiderlandaa`
3. The app should be shown BP data
=> Loading BP data

.github/workflows/push-master-environment.yaml, Dockerfile, docker-compose.staging.yml, docker-compose.yml, kubernetes/cronjob.yaml, kubernetes/demux-deployment.yaml, kubernetes/hapi-deployment.yaml, kubernetes/hasura-deployment.yaml, scripts/deploy.sh, services/frontend/.env.production, services/frontend/.env.staging, services/frontend/.gitignore, services/frontend/Dockerfile, services/frontend/package.json, services/frontend/src/components/card.js, services/frontend/src/components/compare-tool/index.js, services/frontend/src/language/en.json, services/frontend/src/language/es.json, services/frontend/src/models/BlockProducer/blockProducers.js, services/frontend/src/routes/block-producers/block-producer-profile.js, services/frontend/src/routes/block-producers/block-producer-rate.js, services/frontend/src/routes/home/cover.js, services/frontend/src/routes/home/index.js, services/frontend/src/routes/home/subTopic.js
#Update master
2. test the EOS Rate app
=> Update master latest

services/frontend/src/language/en.json, services/frontend/src/language/es.json
1. open eosrate
1. check homepagetexts
=> fix typos on homepage

services/frontend/src/language/en.json, services/frontend/src/language/es.json, services/frontend/src/routes/home/subTopic.js
#Telegram link
1. go home page and click telegram link
=> Telegram link

contracts/rateproducer/README.md, contracts/rateproducer/rateproducer.cpp
rmrate action added for remove rate
Remove a rate
example 1:
cleos -u http://monitor.jungletestnet.io:8888 push action rateproducer rmrate '{"user": "rateproducer", "bp":"alohaeostest"}' -p rateproducer@active
example 2:
cleos -u http://monitor.jungletestnet.io:8888 push action rateproducer rmrate '{"user": "eoscrvoter11", "bp":"eoscrprodo51"}' -p eoscrvoter11@active
=> upd: action added for removing rate

services/frontend/package.json, services/frontend/yarn.lock
#Upgrade anchor library
2. test app
=> Upgrade anchor library

contracts/rateproducer/rateproducer.cpp
this pr included a documentation within the smart contract code
=> Documentation added

services/frontend/package.json, services/frontend/src/routes/help/index.js, services/frontend/src/routes/termsOfUse/index.js, services/frontend/yarn.lock
#472 #471 
- Add Ricardian Contract component (from eoscr-components)
- Add icons in help page
1. yarn
2. run *make dev*
3. go to help page and see the icons
4. go to terms of use page and see the content
=> Add ricardian contract

CONTRIBUTING.md
=> add expalnation about main git branches.

readme.md
=> update readme links

services/frontend/package.json, services/frontend/public/sitemap.xml, services/frontend/src/language/en.json, services/frontend/src/language/es.json, services/frontend/src/routes/index.js, services/frontend/src/routes/termsOfUse/index.js, services/frontend/yarn.lock
Remane Terms of Use to Ricardian Contract
1. run *make dev*
2. go to *http://localhost:3000/*
3. open sideBar menu and click to *Ricardian Contract*
=> Rename terms of use

kubernetes/postgres-statefulset.yaml, kubernetes/storageclass.yml
=> configure a storageclass for the eos rate. refs #509

.github/workflows/push-master-environment.yaml, docs/create-a-release.md, readme.md
=> Create versioning and release workflow

.github/workflows/push-master-environment.yaml, .github/workflows/push-staging-environment.yaml, makefile
=> avoid statefulsets update errors on actions runs refs

.github/workflows/push-master-environment.yaml, .github/workflows/push-staging-environment.yaml
=> fix: add missing workflow env vars

.github/workflows/push-master-environment.yaml, .github/workflows/push-staging-environment.yaml
=> give a specific version to the kubernetes deployment github action

.github/workflows/push-master-environment.yaml
fixes API error
```
!!!! FetchError: request to https://bp.cryptolions.io/v1/chain/get_table_rows failed, reason: getaddrinfo ENOTFOUND bp.cryptolions.io
```
=> Update EOS API Endpoint

kubernetes/cronjob.yaml
Use environmental variables to set cron job pods config
=> Update config values

kubernetes/cronjob.yaml
Reverts eoscostarica/eos-rate#579
=> Revert "Update config values"

kubernetes/hapi-deployment.yaml
Bug documentation: https://github.com/kubernetes/kubernetes/issues/64924
#577
=> fix: Backend Service does not resolve DNS

services/frontend/makefile
=> react app block explorer

services/frontend/src/components/card/index.js, services/frontend/src/components/card/styles.js, services/frontend/src/routes/block-producers/index.js, services/frontend/src/routes/block-producers/styles.js
Resolve #570
1. Fix broke design on bp page
1. Fix broke design on card component
=> Broken design in certains densities

.github/workflows/push-master-environment.yaml, .github/workflows/push-staging-environment.yaml, docker-compose.yml, hapi/src/libs/add-bps-info.js, hapi/src/libs/sync-bps.js, hapi/src/libs/sync-proxies.js, hapi/src/libs/sync-ratings.js, hapi/src/libs/sync-stats.js, hasura/Dockerfile, hasura/config.yaml, hasura/makefile, webapp/yarn.lock
add hasura directories in docker build
=> fix(hasura): fix dir paths

contracts/rateproducer/include/rateproducer.hpp, contracts/rateproducer/include/utils.hpp, contracts/rateproducer/src/rateproducer.cpp, contracts/scripts/compile.sh, contracts/tests/test_unreg_bp.js
Resolves #589 
Resolves #590 
Add method to check if a given user is or not an Eden member
=> feat(rateproducer): check if a given member is eden or not

.github/workflows/push-staging-environment.yaml
Set new API endpoint for Jungle3
=> Update jungle testnet API

hapi/src/libs/add-bps-info.js, webapp/src/components/main-footer/index.js, webapp/src/components/main-footer/styles.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/block-producers/general-information-profile.js
- Update text label for additional resources
- change footer OSS text
=> Update texts for additional resources

hapi/yarn.lock, webapp/package.json, webapp/src/routes/termsOfUse/styles.js, webapp/yarn.lock
1. run `make clean` and `make install`
1. go to Ricardian Contract page
=> Update Ricadian contract component

hasura/metadata/databases/default/tables/public_producers_list.yaml, hasura/metadata/databases/default/tables/public_proxies.yaml
#Add Permissions for public table
1.
1.
1.
=> fix(webapp): add permission for public aggregate tables

webapp/src/components/CompareTool/CompareGraphView.js, webapp/src/components/CompareTool/CompareSliderView.js, webapp/src/components/CompareTool/index.js, webapp/src/components/CompareTool/styles.js, webapp/src/components/FilterBanner/index.js, webapp/src/components/FilterBanner/styles.js, webapp/src/components/Sidebar/index.js, webapp/src/config/filters.js, webapp/src/config/index.js, webapp/src/config/polar-radar-config.js, webapp/src/context/models/producers.js, webapp/src/context/state.context.js, webapp/src/gql/producers.js, webapp/src/routes/BlockProducers/index.js, webapp/src/routes/BlockProducers/styles.js, webapp/src/routes/index.js, webapp/yarn.lock
- Add filter for Block Producer list page
- Add Styling for compare tool component
- Add responsive for Polar Radar Graph 
1. go to `localhost:3000`
1. check Block Producers page
=> fix(webapp): add filters and styling compare tool

webapp/src/components/CompareTool/index.js, webapp/src/components/CompareTool/styles.js, webapp/src/components/FilterBanner/index.js, webapp/src/components/Header/index.js, webapp/src/components/Message/index.js, webapp/src/components/Message/styles.js, webapp/src/context/models/proxies.js, webapp/src/context/state.context.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/language/ko.json, webapp/src/routes/Account/index.js, webapp/src/routes/Account/styles.js, webapp/src/routes/BlockProducers/BlockProducerProfile.js, webapp/src/routes/BlockProducers/BlockProducerRate.js, webapp/src/routes/BlockProducers/styles.js, webapp/src/routes/Proxies/ProxyProfile.js, webapp/src/routes/Proxies/styles.js, webapp/src/utils/get-bp-radar-data.js, webapp/src/utils/modeled-bp-data.js, webapp/src/utils/modeled-proxy-data.js
- Resolve #797 
- Resolve #839 
- Resolve #833 
- Resolve #811 
- Resolve #831 
- Resolve #832 
1. go to `localhost:3000`
1. test the webapp
=> fix(webapp): fix delay login

hapi/src/config/index.js, hapi/src/index.js, hapi/src/utils/index.js
=> (): resolve conflicts

.github/workflows/push-staging-environment.yaml
=> fix(hapi): update hyperion endpoint

.github/workflows/push-master-environment.yaml, .github/workflows/push-staging-environment.yaml, hasura/metadata/databases/default/tables/public_comment.yaml, hasura/metadata/databases/default/tables/public_comment_like.yaml
- Add permissions tables for anonymous role in comment and comment_like tables
=> fix(hasura): add permissions tables

demux/package.json, demux/yarn.lock, docker-compose.yml, hapi/yarn.lock, hasura/Dockerfile, kubernetes/cronjob.yaml, webapp/package.json, webapp/yarn.lock
=> fix(hapi): update cronjob node path

kubernetes/cronjob.yaml
=> fix(hapi): add missing char to env var

docker-compose.yml, hapi/yarn.lock, hasura/Dockerfile, kubernetes/postgres-statefulset.yaml, webapp/package.json, webapp/yarn.lock
=> feat(webapp): update project dependencies

docker-compose.yml, hapi/yarn.lock, hasura/Dockerfile, kubernetes/postgres-statefulset.yaml, webapp/package.json, webapp/yarn.lock
Reverts eoscostarica/eos-rate#944
=> Revert "feat(webapp): update project dependencies"

hapi/src/config/server.config.js, hapi/yarn.lock, webapp/src/layouts/Dashboard/index.js
- Resolves #937
- Update yarn in hapi
1. Run `make run`
2. Go to `localhost:3000`
3. Go to Block Producers > Block Producer Profile
=> Fix Header 

docker-compose.yml, hasura/Dockerfile, kubernetes/postgres-statefulset.yaml
=> update hasura version

webapp/src/routes/Home/index.js
=> Update homepage tweets

webapp/src/components/Card/index.js
- Resolves #979 
1. Run `make run`
2. Go to `localhost:3000`
3. Go to Block Producers
=> fix(webapp): add missing data in card component
